openapi: 3.0.0
info:
  title: Carts API
  version: 1.0.0
  description: API for managing carts and purchases
servers:
  - url: http://localhost:3000 
    description: Development server
paths:
  /:
    get:
      summary: Get all carts
      tags:
        - carts
      security:
        - PUBLIC: []
      responses:
        '200':
          description: Successful operation
  /{cid}:
    get:
      summary: Get a cart by ID
      tags:
        - carts
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      security:
        - PUBLIC: []
      responses:
        '200':
          description: Successful operation
    post:
      summary: Add a cart
      tags:
        - carts
      security:
        - USER: []
      responses:
        '200':
          description: Successful operation
  /{cid}/products/{pid}:
    post:
      summary: Update a cart
      tags:
        - carts
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          required: true
          schema:
            type: string
      security:
        - USER: []
        - PREMIUN: []
      responses:
        '200':
          description: Successful operation
  /delete/{cid}/products/{pid}:
    post:
      summary: Delete a product from a cart
      tags:
        - carts
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          required: true
          schema:
            type: string
      security:
        - USER: []
        - ADMIN: []
        - PREMIUN: []
      responses:
        '200':
          description: Successful operation
  /{cid}/purchase:
    get:
      summary: Add a ticket for a purchase
      tags:
        - carts
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      security:
        - USER: []
      responses:
        '200':
          description: Successful operation